In [1]:
import torch 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)
scalar 

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector 
vector = torch.tensor([7, 7]) # has magnitude and direction
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([
    [7, 8],
    [1, 2]
])

In [9]:
MATRIX

tensor([[7, 8],
        [1, 2]])

In [11]:
MATRIX[1]

tensor([1, 2])

In [12]:
MATRIX.shape

torch.Size([2, 2])

### Random tensors

In [16]:
random_tensor = torch.rand(5, 5, 5)
random_tensor

tensor([[[0.2016, 0.6661, 0.3580, 0.6147, 0.0195],
         [0.0607, 0.6562, 0.5198, 0.9113, 0.4461],
         [0.8007, 0.5317, 0.0449, 0.1892, 0.7773],
         [0.4210, 0.1466, 0.0340, 0.6971, 0.4014],
         [0.7394, 0.4942, 0.9235, 0.3341, 0.2288]],

        [[0.4487, 0.9697, 0.5920, 0.5289, 0.4282],
         [0.2181, 0.9029, 0.5455, 0.8327, 0.3364],
         [0.3704, 0.8530, 0.7726, 0.5263, 0.0336],
         [0.7882, 0.3481, 0.7898, 0.0420, 0.8715],
         [0.0149, 0.5120, 0.6448, 0.7472, 0.1231]],

        [[0.4185, 0.2978, 0.1790, 0.6615, 0.2040],
         [0.6574, 0.5232, 0.7441, 0.1681, 0.8769],
         [0.4805, 0.2180, 0.7058, 0.7810, 0.8902],
         [0.3621, 0.5923, 0.9577, 0.6981, 0.3614],
         [0.9333, 0.8304, 0.7150, 0.9263, 0.6005]],

        [[0.1905, 0.2017, 0.4141, 0.0638, 0.5004],
         [0.2156, 0.4987, 0.8950, 0.7225, 0.7040],
         [0.8606, 0.2314, 0.9100, 0.4211, 0.7471],
         [0.7180, 0.4469, 0.7064, 0.9254, 0.1679],
         [0.0871, 0.0699,

In [18]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [21]:
# create a tensor of all zeros
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
# create a tensor of all ones
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [31]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# Creating tensors like 
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [36]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], 
    dtype=torch.float32, # what datatype is the tensor
    device=None, # moves tensor to a specific device (cpu or gpu)
    requires_grad=False
)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_32_tensor.dtype

torch.float16

In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [41]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [42]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [44]:
float_32_tensor.device

device(type='cpu')

### Manipulating tensors

Tensor operation include: 
- Addition
- Substraction
- Multiplication (element-wise and matrix wise)
- Division

In [52]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [53]:
# Multiply by 10
tensor * 10
tensor 

tensor([1, 2, 3])

In [54]:
# Subtract 
tensor - 10

tensor([-9, -8, -7])

In [55]:
# Try out PyTorch in-build functions 
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [56]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Element-wise vs matrix multiplication (dot-product)

Two rules:
1. The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work 
* (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimension
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [65]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [69]:
torch.matmul(torch.rand(10, 3), torch.rand(3, 10))

tensor([[0.3795, 1.1120, 0.2806, 1.2942, 0.3526, 0.4113, 0.5603, 0.8797, 0.4758,
         0.8329],
        [0.7012, 1.7413, 0.7936, 1.8377, 0.7703, 0.8707, 1.3100, 1.4658, 0.9561,
         1.0340],
        [0.4265, 1.0793, 0.2772, 1.2565, 0.4185, 0.4496, 0.5197, 0.8919, 0.5144,
         0.8928],
        [0.5162, 1.1496, 0.4646, 1.2486, 0.5641, 0.5962, 0.7545, 0.9993, 0.6584,
         0.8386],
        [0.4764, 1.1726, 0.5685, 1.2190, 0.5319, 0.6031, 0.9270, 0.9917, 0.6589,
         0.6609],
        [0.3837, 0.8480, 0.5715, 0.7956, 0.4714, 0.5309, 0.8712, 0.7511, 0.5639,
         0.3412],
        [0.8439, 1.4877, 0.8304, 1.4993, 1.0089, 1.0070, 1.1998, 1.4198, 1.0821,
         1.0763],
        [0.7186, 1.5683, 0.7676, 1.6307, 0.8182, 0.8772, 1.2065, 1.3796, 0.9550,
         1.0016],
        [0.5209, 1.4378, 0.5121, 1.5930, 0.5286, 0.6149, 0.9147, 1.1649, 0.6911,
         0.9399],
        [0.6436, 0.5968, 0.7200, 0.4051, 0.8864, 0.8083, 0.8538, 0.7886, 0.8299,
         0.4293]])

In [57]:
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [58]:
torch.matmul(tensor, tensor)

tensor(14)

In [59]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [60]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 1.01 ms


tensor(14)

In [62]:
%%time 
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Shape errors

In [77]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4], 
                         [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# we need to fix the tensor shape issues, we can manipulate the shape of a tensor with transpose
# A transpose switches the axes/ dims of a tensor

print(tensor_b.T)
torch.mm(tensor_a, tensor_b.T)

tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Min, Max, Mean, Sum, etc

In [3]:
x = torch.arange(0, 100, 10)

In [4]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [6]:
# # find min
torch.mean(x.type(torch.float32))

tensor(45.)

In [7]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Positional min and max

In [8]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
x.argmin()

tensor(0)

In [12]:
x[0]

tensor(0)

In [10]:
x.argmax()

tensor(9)

In [11]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors

In [13]:
x = torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [16]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [18]:
# Change the view
z = x.view(1, 9) # view shares the same memeory as x, changing z changes x
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [20]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [23]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [24]:
# torch.squeeze() removes all 1 dimensions form a tensor
x_reshaped.shape

torch.Size([1, 9])

In [29]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [32]:
x_squeezed = x_reshaped.squeeze()
x_reshaped.squeeze().shape

torch.Size([9])

In [35]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [38]:
# torch.permute - rearranges the dimension of a target in a specified order
x = torch.randn(2, 3, 5)
print(x), print(x.size())

y = torch.permute(x, (2, 0, 1))
print(y), print(y.size())

tensor([[[ 0.6430,  0.0879, -1.8766,  0.1517, -0.6894],
         [ 0.3492,  2.4011,  0.9110, -0.9511,  0.5971],
         [ 0.9434,  1.0861,  0.2083,  1.1340, -1.1143]],

        [[-1.0077, -0.1237, -0.4185,  0.2589,  1.3024],
         [-1.4137, -1.4290,  0.2725,  0.9760,  2.3155],
         [-0.5700,  1.6782,  0.0868,  0.5627,  0.1838]]])
torch.Size([2, 3, 5])
tensor([[[ 0.6430,  0.3492,  0.9434],
         [-1.0077, -1.4137, -0.5700]],

        [[ 0.0879,  2.4011,  1.0861],
         [-0.1237, -1.4290,  1.6782]],

        [[-1.8766,  0.9110,  0.2083],
         [-0.4185,  0.2725,  0.0868]],

        [[ 0.1517, -0.9511,  1.1340],
         [ 0.2589,  0.9760,  0.5627]],

        [[-0.6894,  0.5971, -1.1143],
         [ 1.3024,  2.3155,  0.1838]]])
torch.Size([5, 2, 3])


(None, None)

In [3]:
x_original = torch.rand(224, 224, 3)
x_permuted = x_original.permute(2, 0, 1)

print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [4]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

In [2]:
import torch

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [10]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [12]:
# Let's index on our new tensor
x[0]

tensor([1, 2, 3])

In [23]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [17]:
# Let's index on the most inner bracket 
x[0][2][2]

tensor(9)

In [18]:
# You can also use ":" to select all of a target dim
x[:, 0]

tensor([[1, 2, 3]])

In [20]:
# Get all values of 0th and 1st dim and only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [21]:
# Get all vales of the 0 dimension but only the 1 index value of 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [22]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [24]:
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [31]:
# NumPy array to tensor 
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [32]:
array.dtype

dtype('float64')

In [33]:
tensor.dtype

torch.float32

In [34]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [38]:
# Change value of array, what will this do to tensor? 
array = array + 1 
array, tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [39]:
# Tensor to NumPy array 
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [40]:
# Change the tensor, what happens to `numpy_tensor`? 
tensor = tensor + 1
tensor

tensor([2., 2., 2., 2., 2., 2., 2.])

### Reproducability
Take the random out of random.

In [71]:
SEED = 1337
torch.manual_seed(SEED)
tensor_a = torch.rand(3, 4)
torch.manual_seed(SEED)
tensor_b = torch.rand(3, 4)

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([[0.0783, 0.4956, 0.6231, 0.4224],
        [0.2004, 0.0287, 0.5851, 0.6967],
        [0.1761, 0.2595, 0.7086, 0.5809]])
tensor([[0.0783, 0.4956, 0.6231, 0.4224],
        [0.2004, 0.0287, 0.5851, 0.6967],
        [0.1761, 0.2595, 0.7086, 0.5809]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on GPUs

In [72]:
!nvidia-smi

Mon Jan  8 20:50:17 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.25                 Driver Version: 536.25       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA T1000                 WDDM  | 00000000:01:00.0 Off |                  N/A |
| 35%   32C    P8              N/A /  50W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [73]:
# Check for GPU access for PyTorch
torch.cuda.is_available()

True

In [76]:
# Setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"

In [77]:
# Count number of GPUs
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [84]:
tensor = torch.tensor([1, 2, 3]).to(device)
print(tensor)

tensor([1, 2, 3], device='cuda:0')


In [88]:
# Moving back to cpu
tensor.cpu().numpy()

array([1, 2, 3], dtype=int64)

In [89]:
tensor

tensor([1, 2, 3], device='cuda:0')