In [1]:
import torch 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
scalar = torch.tensor(7)
scalar 

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector 
vector = torch.tensor([7, 7]) # has magnitude and direction
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([
    [7, 8],
    [1, 2]
])

In [9]:
MATRIX

tensor([[7, 8],
        [1, 2]])

In [11]:
MATRIX[1]

tensor([1, 2])

In [12]:
MATRIX.shape

torch.Size([2, 2])

### Random tensors

In [16]:
random_tensor = torch.rand(5, 5, 5)
random_tensor

tensor([[[0.2016, 0.6661, 0.3580, 0.6147, 0.0195],
         [0.0607, 0.6562, 0.5198, 0.9113, 0.4461],
         [0.8007, 0.5317, 0.0449, 0.1892, 0.7773],
         [0.4210, 0.1466, 0.0340, 0.6971, 0.4014],
         [0.7394, 0.4942, 0.9235, 0.3341, 0.2288]],

        [[0.4487, 0.9697, 0.5920, 0.5289, 0.4282],
         [0.2181, 0.9029, 0.5455, 0.8327, 0.3364],
         [0.3704, 0.8530, 0.7726, 0.5263, 0.0336],
         [0.7882, 0.3481, 0.7898, 0.0420, 0.8715],
         [0.0149, 0.5120, 0.6448, 0.7472, 0.1231]],

        [[0.4185, 0.2978, 0.1790, 0.6615, 0.2040],
         [0.6574, 0.5232, 0.7441, 0.1681, 0.8769],
         [0.4805, 0.2180, 0.7058, 0.7810, 0.8902],
         [0.3621, 0.5923, 0.9577, 0.6981, 0.3614],
         [0.9333, 0.8304, 0.7150, 0.9263, 0.6005]],

        [[0.1905, 0.2017, 0.4141, 0.0638, 0.5004],
         [0.2156, 0.4987, 0.8950, 0.7225, 0.7040],
         [0.8606, 0.2314, 0.9100, 0.4211, 0.7471],
         [0.7180, 0.4469, 0.7064, 0.9254, 0.1679],
         [0.0871, 0.0699,

In [18]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [21]:
# create a tensor of all zeros
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
# create a tensor of all ones
ones = torch.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [31]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# Creating tensors like 
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [36]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], 
    dtype=torch.float32, # what datatype is the tensor
    device=None, # moves tensor to a specific device (cpu or gpu)
    requires_grad=False
)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_32_tensor.dtype

torch.float16

In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [41]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [42]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [44]:
float_32_tensor.device

device(type='cpu')

### Manipulating tensors

Tensor operation include: 
- Addition
- Substraction
- Multiplication (element-wise and matrix wise)
- Division

In [52]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [53]:
# Multiply by 10
tensor * 10
tensor 

tensor([1, 2, 3])

In [54]:
# Subtract 
tensor - 10

tensor([-9, -8, -7])

In [55]:
# Try out PyTorch in-build functions 
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [56]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Element-wise vs matrix multiplication (dot-product)

Two rules:
1. The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work 
* (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimension
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [65]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [69]:
torch.matmul(torch.rand(10, 3), torch.rand(3, 10))

tensor([[0.3795, 1.1120, 0.2806, 1.2942, 0.3526, 0.4113, 0.5603, 0.8797, 0.4758,
         0.8329],
        [0.7012, 1.7413, 0.7936, 1.8377, 0.7703, 0.8707, 1.3100, 1.4658, 0.9561,
         1.0340],
        [0.4265, 1.0793, 0.2772, 1.2565, 0.4185, 0.4496, 0.5197, 0.8919, 0.5144,
         0.8928],
        [0.5162, 1.1496, 0.4646, 1.2486, 0.5641, 0.5962, 0.7545, 0.9993, 0.6584,
         0.8386],
        [0.4764, 1.1726, 0.5685, 1.2190, 0.5319, 0.6031, 0.9270, 0.9917, 0.6589,
         0.6609],
        [0.3837, 0.8480, 0.5715, 0.7956, 0.4714, 0.5309, 0.8712, 0.7511, 0.5639,
         0.3412],
        [0.8439, 1.4877, 0.8304, 1.4993, 1.0089, 1.0070, 1.1998, 1.4198, 1.0821,
         1.0763],
        [0.7186, 1.5683, 0.7676, 1.6307, 0.8182, 0.8772, 1.2065, 1.3796, 0.9550,
         1.0016],
        [0.5209, 1.4378, 0.5121, 1.5930, 0.5286, 0.6149, 0.9147, 1.1649, 0.6911,
         0.9399],
        [0.6436, 0.5968, 0.7200, 0.4051, 0.8864, 0.8083, 0.8538, 0.7886, 0.8299,
         0.4293]])

In [57]:
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [58]:
torch.matmul(tensor, tensor)

tensor(14)

In [59]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [60]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 1.01 ms


tensor(14)

In [62]:
%%time 
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Shape errors

In [77]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4], 
                         [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# we need to fix the tensor shape issues, we can manipulate the shape of a tensor with transpose
# A transpose switches the axes/ dims of a tensor

print(tensor_b.T)
torch.mm(tensor_a, tensor_b.T)

tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])